# Generated by Django 4.0.5 on 2022-06-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
