# Generated by Django 4.0.5 on 2022-06-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionAPI', '0007_remove_question_answers_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
